/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticationResponse { 
    token?: string;
    nickname?: string;
    email?: string;
    status?: AuthenticationResponse.StatusEnum;
}
export namespace AuthenticationResponse {
    export const StatusEnum = {
        Online: 'ONLINE',
        Offline: 'OFFLINE',
        Away: 'AWAY',
        DoNotDisturb: 'DO_NOT_DISTURB'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


