/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Message { 
    id?: string;
    content?: string;
    sendId?: number;
    senderNickname?: string;
    conversationId?: number;
    channelId?: number;
    timestamp?: string;
}

